version: "3.5"

services:
  furnitureStore:
    image: furniture-store
    ports:
      - "80:3000"
    environment:
      BACKEND_HOST: "178.154.201.116"

  furnitureStoreSrv:
    image: furniture-store-srv
    ports:
      - "8080:8080"
